export interface Message {
  /**
   * The role of the sender of the message.
   * - 'user': Represents a message from the end-user.
   * - 'assistant': Represents a message generated by the AI assistant.
   * - 'system': Represents a system-level instruction or context provided to the assistant.
   */
  role: 'user' | 'assistant' | 'system';
  /**
   * The actual content of the message.
   */
  content: string;
}

/**
 * Defines a type for a resource's origin or location.
 * This accommodates various ways model or tokenizer files can be specified and loaded:
 * - A string representing a local asset using `require()` (for files typically < 512MB).
 * - A remote URL string (e.g., 'https://...') for larger files or external hosting.
 * - A local file system path string (e.g., 'file:///...') for user-provided files.
 * This type is flexible to cover different model loading strategies.
 */
export type ResourceSource = string | number | object;

/**
 * Defines the structure of a search result from a vector store.
 */
export interface SearchResult {
  id: string;
  content: string;
  metadata?: Record<string, any>;
  similarity: number;
}
